export const ACTION_TYPES = {
  ADD_ROW: 'ADD_ROW',
  DELETE_ROW: 'DELETE_ROW',
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  ADD_CHILD_CATEGORY: 'ADD_CHILD_CATEGORY',
  MOVE_UP_CATEGORY: 'MOVE_UP_CATEGORY',
  MOVE_DOWN_CATEGORY: 'MOVE_DOWN_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  CHANGE_CELL: 'CHANGE_CELL',
  MOVE_IMAGE: 'MOVE_IMAGE',
  ADD_IMAGE: 'ADD_IMAGE'
}