export const ACTION_TYPES = {
  ADD_ROW: 'ADD_ROW',
  MOVE_UP_ROW: 'MOVE_UP_ROW',
  MOVE_DOWN_ROW: 'MOVE_DOWN_ROW',
  DELETE_ROW: 'DELETE_ROW',
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  ADD_CHILD_CATEGORY: 'ADD_CHILD_CATEGORY',
  MOVE_UP_CATEGORY: 'MOVE_UP_CATEGORY',
  MOVE_DOWN_CATEGORY: 'MOVE_DOWN_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  CHANGE_CELL: 'CHANGE_CELL',
  MOVE_IMAGE: 'MOVE_IMAGE',
  ADD_IMAGE: 'ADD_IMAGE',

  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE'
}