export const COLUMN_TYPES = {
  ID: 'ID',
  CATEGORY_ID: 'CATEGORY_ID',
  HIDDEN: 'HIDDEN',
  CHECK: 'CHECK',
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  LABEL: 'LABEL',
  TEXT: 'TEXT',
  IMAGES: 'IMAGES'
}

export const INPUT_TYPES = {
  TEXTAREA: 'TEXTAREA',
  INPUT: 'INPUT'
}